<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AudioSwitcher.AudioApi.CoreAudio" Version="3.0.3" />
    <PackageReference Include="HidSharp" Version="2.6.4" />
    <PackageReference Include="InputSimulatorPlus" Version="1.0.7" />
    <PackageReference Include="LibreHardwareMonitorLib" Version="0.9.3" />
    <PackageReference Include="Nefarius.Drivers.HidHide" Version="3.4.0" />
    <PackageReference Include="Nefarius.ViGEm.Client" Version="1.21.256" />
    <PackageReference Include="NvAPIWrapper.Net" Version="0.8.1.101" />
    <PackageReference Include="SharpDX.Direct3D11" Version="4.2.0" />
    <PackageReference Include="SharpDX.DirectInput" Version="4.2.0" />
    <PackageReference Include="SharpDX.DXGI" Version="4.2.0" />
    <PackageReference Include="SharpDX.XInput" Version="4.2.0" />
    <PackageReference Include="System.Diagnostics.PerformanceCounter" Version="10.0.10" />
    <PackageReference Include="System.DirectoryServices.AccountManagement" Version="10.0.8" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.8" />
    <PackageReference Include="System.Text.Json" Version="10.0.8" />
    <PackageReference Include="WPF-UI" Version="3.0.4" />
  </ItemGroup>

  <ItemGroup>
    <None Update="juegos_perfiles.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <EmbeddedResource Include="WindowsLikeSteamOS\Shaders\CRT_VS.cso" />
    <EmbeddedResource Include="WindowsLikeSteamOS\Shaders\CRT_PS.cso" />
  </ItemGroup>

</Project>