<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>icon.ico</ApplicationIcon>
    <AssemblyName>SteamOS</AssemblyName>
    <AssemblyTitle>SteamOS</AssemblyTitle>
    <Product>SteamOS</Product>
    <Title>SteamOS</Title>

    <!-- Propiedades de compilación y empaquetado autocontenido -->
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    
    <!-- Optimizaciones de rendimiento (Arranque rápido) -->
    <TieredCompilation>true</TieredCompilation>
    <TieredCompilationQuickJit>true</TieredCompilationQuickJit>
    <DebugType>None</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AudioSwitcher.AudioApi.CoreAudio" Version="3.0.3" />
    <PackageReference Include="HidSharp" Version="2.6.4" />
    <PackageReference Include="InputSimulatorPlus" Version="1.0.7" />
    <PackageReference Include="LibreHardwareMonitorLib" Version="0.9.3" />
    <PackageReference Include="Nefarius.Drivers.HidHide" Version="3.4.0" />
    <PackageReference Include="Nefarius.ViGEm.Client" Version="1.21.256" />
    <PackageReference Include="NvAPIWrapper.Net" Version="0.8.1.101" />
    <PackageReference Include="SharpDX.Direct3D11" Version="4.2.0" />
    <PackageReference Include="SharpDX.DirectInput" Version="4.2.0" />
    <PackageReference Include="SharpDX.DXGI" Version="4.2.0" />
    <PackageReference Include="SharpDX.XInput" Version="4.2.0" />
    <PackageReference Include="System.Diagnostics.PerformanceCounter" Version="10.0.10" />
    <PackageReference Include="System.DirectoryServices.AccountManagement" Version="10.0.8" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.8" />
    <PackageReference Include="System.Text.Json" Version="10.0.8" />
    <PackageReference Include="WPF-UI" Version="3.0.4" />
  </ItemGroup>

  <ItemGroup>
    <None Update="juegos_perfiles.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <Target Name="AutoPublish" AfterTargets="Build" Condition="'$(IsPublishing)' != 'true'">
    <Exec Command="dotnet publish -c $(Configuration) -r win-x64 --no-build -p:IsPublishing=true" />
    <Copy SourceFiles="$(OutputPath)publish\SteamOS.exe" DestinationFolder="bin\$(Configuration)\" />
  </Target>

</Project>