<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>icon.ico</ApplicationIcon>
    <AssemblyName>SteamOS_Config</AssemblyName>
    <AssemblyTitle>SteamOS Configurator</AssemblyTitle>
    <Product>SteamOS</Product>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="icon.ico" />
    <Resource Include="icon.png" />
    <EmbeddedResource Include="icon.ico" LogicalName="icon.ico" />
    <EmbeddedResource Include="icon.png" LogicalName="icon.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="WPF-UI" Version="3.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SteamOS.Core\SteamOS.Core.csproj" />
  </ItemGroup>

</Project>
