<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>icon.ico</ApplicationIcon>
    <AssemblyName>SteamOS_Setup</AssemblyName>
    <AssemblyTitle>SteamOS Installer</AssemblyTitle>
    <Product>SteamOS</Product>

    <!-- Propiedades para instalador único distribuible -->
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <DebugType>None</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="icon.ico" />
    <Resource Include="icon.png" />
    <EmbeddedResource Include="icon.ico" LogicalName="icon.ico" />
    <EmbeddedResource Include="icon.png" LogicalName="icon.png" />
    <EmbeddedResource Include="..\SteamOS.Shell\bin\Release\net8.0-windows\win-x64\publish\SteamOS_Shell.exe" LogicalName="SteamOS_Shell.exe" Condition="Exists('..\SteamOS.Shell\bin\Release\net8.0-windows\win-x64\publish\SteamOS_Shell.exe')" />
    <EmbeddedResource Include="..\SteamOS.Config\bin\Release\net8.0-windows\win-x64\publish\SteamOS_Config.exe" LogicalName="SteamOS_Config.exe" Condition="Exists('..\SteamOS.Config\bin\Release\net8.0-windows\win-x64\publish\SteamOS_Config.exe')" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="WPF-UI" Version="3.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SteamOS.Core\SteamOS.Core.csproj" />
  </ItemGroup>

</Project>
